### ISSUE TITLE
Python binding broken in Ubuntu

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#631]
**Issue**

The current python binding is broken on Ubuntu. It crashes with the following error message:

```
florian@florian-ubuntu20:/usr/share/ecal/samples/python/person_snd$ python3 person_snd.py 
eCAL v5.10.0-alpha-53-g78852f77 (21.04.2022)

Traceback (most recent call last):
  File "person_snd.py", line 67, in <module>
    main()  
  File "person_snd.py", line 40, in main
    pub = ProtoPublisher("person", person_pb2.Person)
  File "/usr/local/lib/python3.8/dist-packages/ecal/core/publisher.py", line 89, in __init__
    topic_desc = pb_helper.get_descriptor_from_type(type_)
  File "/usr/local/lib/python3.8/dist-packages/ecal/proto/helper.py", line 54, in get_descriptor_from_type
    add_proto_desc(file_desc_set, desc_file, tracing_set)
  File "/usr/local/lib/python3.8/dist-packages/ecal/proto/helper.py", line 37, in add_proto_desc
    add_proto_desc(file_desc_set, dep, inserted_files)
  File "/usr/local/lib/python3.8/dist-packages/ecal/proto/helper.py", line 41, in add_proto_desc
    file_desc_set.file.append(current_file_desc)
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
```

I assume, the following commit is the issue: https://github.com/continental/ecal/commit/1e1bf4f168c226b79f16bde29b6e1b4f09328fd0

I have tested on:
- Ubuntu 20.04
- with Python 3.8.10
- and Protobuf 3.6.1

I have re-generated the `pb2.py` files as a test, but it did not solve the issue.

The python binding works fine on Windows 10 with Protobuf 3.11.4.
