### ISSUE TITLE
Build failed on Raspberry Pi with Raspbian Buster and GCC 8.3

### ISSUE THREAD

**Issue by mgdelta** [continental/ecal#12]
Hi eCAL team,

trying to build your system on a Raspberry Pi 3B+ fails. Build stops first time when building the executable ecal_topic. The linker complains about undefined reference to
__atomic_load_8
__atomic_store_8
__atomic_fetch_add_8

It looks like a problem linking to -latomic which is necessary on armhf systems. 

I'm using an actual raspbian (Buster) with GCC 8.3
During build there are a lot of warnings due to some changes after GCC 7.4. 
Maybe the -latomic thing is a problem of using GCC 8 or cmake is doing something ugly.

Can you confirm my problem or is it an issue on my side/system?

Thanks!!

**Comment by Blutkoete** [comment]
I'm not associated with the eCAL team in any way, but I wanted to add that this may not be related to Raspberry Pi 3 or armhf per se, as both the old and the current release build fine with gcc 8.5.0 on my Raspberry Pi 3's running ArchLinuxARM. One main difference is probably that I'm building against the ArchLinuxARM's own versions of protobuf, tclap, asio and simpleini, not the bundled ones.

This is not solving your issue, I know, but maybe it helps someone pinpointing the problem.

**Comment by Kerstin-Keller** [comment]
So it seems that so far we haven't been building for platforms which do require the special `-latomic` linker flag in order to use the `std::atomic` objects.

I suspect the appropriate `target_link_libraries` command is missing for the eCAL core library
https://github.com/continental/ecal/blob/04a1093bfbb6659763320d9791a40c5c180a3135/ecal/core/src/CMakeLists.txt#L378-L397
 and maybe some of the samples.

However, it is not quite clear to me, under which compilation conditions (compiler, platform, e.g. ) the extra linker arguments are necessary.

Amongst others I found [this example](https://phabricator.kde.org/D16184) and [this example from llvm](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CheckAtomic.cmake) where they are trying to detect if the linker argument is necessary.

I am just a bit astonished, as this is / should be(?) part of the standard library, that this is not somehow handled by CMake and the generic flags it sets for one platform (e.g. when enabling the C++11  standard).

**Comment by rex-schilasky** [comment]
@mgdelta did you succeed with the build ?

**Comment by rex-schilasky** [comment]
No more feedback here .. just close it.
